project:
  type: book
  output-dir: docs
  
book:
  title: "Introdução à Inferência Bayesiana"
  author: "James D Santos"
  date: "10/03/2023"
  chapters:
    - index.qmd
    - summary.qmd
    - intro.qmd
    - conjugada.qmd
    - estimacao.qmd
    - teste.qmd
    - normal.qmd
    - negativeBinomial.qmd
    - aproximacaoNormal.qmd
    - misturas.qmd
    - poisson.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt
  epub:
    cover-image: cover.png