project:
  type: book
  output-dir: docs
  
book:
  title: "Introdução à Inferência Bayesiana"
  author: "James D Santos"
  date: "08/05/2025"
  chapters:
    - index.qmd
    - summary.qmd
    - intro.qmd
    - conjugada.qmd
    - estimacao.qmd
    - bernoulli.qmd
    - teste.qmd
    - poisson.qmd
    - exponencial.qmd
    - normal.qmd
    - normal_multi.qmd
    - aproximacaoNormal.qmd
    - regressao.qmd
    - logistica.qmd
    - loglinear.qmd
    - negativeBinomial.qmd
    - misturas.qmd
    - mcmc.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
