# Famílias conjugadas



## Dados que serão utilizados neste capítulo


```{r}
require(gsheet)
url <- 'https://docs.google.com/spreadsheets/d/1dLDCjA9a8UgXA9sJ1TNCVvRCDFITalewGkHlc__Eg20/edit?usp=sharing' 
dt <- gsheet2tbl(url)
head(dt)
```



## Família de distribuições conjugadas


::: {#def-Priori conjugada}
Dizemos que a priori $f(\boldsymbol{\theta})$ é conjugada para a verossimilhança $L(\boldsymbol{\theta})$ se *priori* e *posteriori* pertencem à mesma família de distribuições.
:::

::: {#exm-}
Sejam $X_1,\ldots,X_n$ variáveis aleatórias independentes com $X|\theta\sim \hbox{Bernoulli}(\theta)$ e $\theta\sim\hbox{Beta}(a,b)$. Então

$$\begin{align}
    f(\theta|\boldsymbol{x})&\varpropto L(\theta)f(\theta) = \underbrace{\theta^{\sum_{i=1}^{n}x_i} (1-\theta)^{n-\sum_{i=1}^{n}x_i}}_{L(\theta)}\underbrace{\theta^{a-1}(1-\theta)^{b-1}}_{f(\theta)}\\
    &=\theta^{a+\sum_{i=1}^n x_i-1}(1-\theta)^{b+n-\sum_{i=1}^{n}x_i-1},
    \end{align}$$
logo $\theta|\boldsymbol{x}\sim\hbox{Beta}(a+\sum_{i=1}^{n}x_i,b+n-\sum_{i=1}^{n}x_i)$ e a *priori* beta é conjugada para a verossimilhança Bernoulli.
:::

Famílias conjugadas são extremamente úteis tanto sob o ponto de vista algébrico quanto computacional. Entretanto, note que a definição de família conjugada é ampla. Por exemplo, *priori* e *posteriori* sempre pertencem à grande família de todas as distribuições de probabilidade, sendo esta a família conjugada trivial.

Famílias conjugadas não triviais são raras, existindo principalmente quando a distribuição condicional dos dados pertence à família exponencial.

::: {#def-Família exponencial}
<strong>Definição</strong> Considere que $\Theta$ tem dimensão $k$. Dizemos que $X|\boldsymbol{\theta}$ pertence à família exponencial (natural) se $$f(x|\boldsymbol{\theta})=h(x)a(\boldsymbol{\theta})\exp\left\{\sum_{j=1}^k t_j(x)\theta_j\right\},$$ onde $\mathcal{X}$ não depende de $\boldsymbol{\theta}$. Além disso, para a amostra (iid )$X_1,\ldots,X_n|\boldsymbol{\theta}$, $$f(\boldsymbol{x}|\boldsymbol{\theta})=h(\boldsymbol{x})a(\boldsymbol{\theta})^n\exp\left\{\sum_{j=1}^k T_j\theta_j\right\},$$ onde $T_j=\sum_{i=1}^{n}t_j(x_i)$
:::

::: {#thm-}
Se $X|\boldsymbol{\theta}$ pertence à família exponencial, então $$f(\boldsymbol{\theta})=c(\boldsymbol{r},s)a(\boldsymbol{\theta})^s\exp\left\{\sum_{j=1}^k r_j\theta_j\right\}$$ é uma *priori* conjugada (ver O'Hagan (2005) para a existência dessa distribuição). A *posteriori* será dada por $$f(\boldsymbol{\theta}|\boldsymbol{x})=c\left(\sum_{j=1}^k r_j+T_j,s+n\right)a(\boldsymbol{\theta})^{s+n}\exp\left\{\sum_{j=1}^k(r_j+T_j)\theta_j\right\}$$
:::

::: {.alert .alert-success}
<strong>Prova</strong>

$$\begin{align}
f(\boldsymbol{\theta}|\boldsymbol{x})&\varpropto \underbrace{a(\boldsymbol{\theta})^ne^{\sum_{j=1}^kT_j\theta_k}}_{L(\boldsymbol{\theta})}\underbrace{a(\boldsymbol{\theta})^s e^{\sum_{j=1}^k r_j\theta_k}}_{f(\boldsymbol{\theta})}\\
&a(\boldsymbol{\theta})^{n+s}e^{(\sum_{j=1}^{k}T_j+r_j)\theta_j}
\end{align}$$
:::

Considere que $\boldsymbol{\theta}\sim C(\boldsymbol{r},s)$ é a distribuição conjugada da verossimilhança. Isto implica em $\boldsymbol{\theta}|\boldsymbol{x}\sim\hbox{C}(\boldsymbol{T}+\boldsymbol{r},s+n)$. Note que a *posteriori* atualiza a informação de $s$ para $s+n$ e de $r_j$ para $T_j+r_j$. Logo, se imaginarmos que a priori é um experimento hipotético, $s$ seria o tamanho da amostra e $\boldsymbol{r}$ seriam as estatísticas suficientes deste modelo.


Abaixo, segue uma lista de algumas prioris conjugadas para modelos na família exponencial.

$$\begin{array}{c|c|c}\hline
\text{Modelo} & \text{Priori} & \text{Posteriori} \\ \hline
\text{Bernoulli}(\theta) & \text{Beta}(a,b) & \text{Beta}(a+\sum_i x_i, b+n-\sum_i x_i) \\ \hline
\text{Poisson}(\lambda) & \text{Gama}(a,b) & \text{Gama}(a+\sum_i x_i, b+n) \\ \hline
\text{Multinomial}(p_1,\ldots,p_k) & \text{Dirichlet}(a_1,\ldots,a_k) & \text{Dirichlet}(a_1+x_1,\ldots,a_k+x_k) \\
\text{Exponencial}(\lambda) & \text{Gama}(a,b) & \text{Gama}(a+n, b+x_i) \\
\text{Normal}(\mu,\phi^{-1})&\text{Normal-Gama}(m_0,n_0,v_0,s_0^2)&
\text{Normal-Gama}(m_1,n_0+n,v_0+n,s_1^2)\\
& & m_1= \frac{n}{n_1}\bar{x}+\frac{n_0}{n_1}m_0\\
& & s_1^2=\frac{n_0n}{n_1^2}(\bar{x}-m_0)^2 + \frac{(n-1)s^2+n_0 s_0^2}{n_1} \\ \hline
\end{array}
$$


## Prioris conjugadas fora da família exponencial

Famílias conjugadas fora da família exponencial são raras. Seja $X_1,\ldots,X_n$ variáveis aleatória independentes com $X_1|\phi,\psi\sim\hbox{Binomial Negativa}(\psi,\phi)$, onde

$$f(x|\phi,\psi)=\frac{\Gamma(x+\psi)}{\Gamma(\psi)x!}\phi^\psi (1-\phi)^x,$$
com $\psi>0$, $\phi\in(0,1)$ e $x\in\mathbb{N}$. Se $\psi$ é conhecido, então $$L(\boldsymbol{\theta})=\underbrace{\left[\frac{\prod_{i=1}^n\Gamma(x_i+\psi)}{\Gamma(\psi)^n\prod_{i=1}^n x_i!}\right]}_{h(\boldsymbol{x})}\underbrace{\phi^{n\psi}}_{a(\phi)}\exp\left\{ \underbrace{\sum_{i=1}^n x_i}_{t(\boldsymbol{x})} \underbrace{\log(1-\phi)}_{w(\phi)}\right\} $$

Então, 
$$\begin{align}
f(\phi|\psi)&=c(r,s)a(\phi)^s e^{rw(\phi)}\\
&=c(r,s)\phi^{s\psi}(1-\phi)^{r}
\end{align}$$
é uma $*priori*$ conjugada. Da expressão acima segue que $\phi|\psi \sim \hbox{Beta}(s\psi+1,r+1)$. A $*posteriori*$ (condicional) por sua vez é dada por 
$$f(\phi|\boldsymbol{x},\psi)\varpropto \phi^{\psi(s+n)}(1-\phi)^{r+\sum_{i=1}^{n}x_i},$$
onde ainda $\phi|\psi,\boldsymbol{x}\sim\hbox{Beta}(\psi(s+n)+1,r+\sum_{i=1}^{n}x_i+1)$ Note que para fazer a inferência completa, ainda necessitamos de $\psi|\boldsymbol{x}$, uma vez que $$f(\phi,\psi|\boldsymbol{x})=f(\phi|\psi,\boldsymbol{x})f(\psi|\boldsymbol{x}).$$
Outro método de obter a conjunta $(\phi,\psi|\boldsymbol{x})$, sem a necessidade de calcular $\psi|\boldsymbol{x}$ será discutido na próxima aula.

