## O modelo normal

## A distribuição normal-gama

Dizemos que $(X,Y)\sim NG(\mu,n_0,\nu,d^2)$ (lê-se normal-gama) se sua função densidade conjunta é dada por

$$f(x,y)\propto y^{\frac{\nu+1}{2}-1}\exp\left\{-\frac{y}{2}n_0\left[(x-\mu)^2 + d^2\right]\right\}$$

onde $\mu,x\in\mathbb{R}$ e $d,y,c\in\mathbb{R}_+$. Colocando os termos que não dependem de $x$ junto com a constante de proporcionalidade, podemos mostrar que

$$f(x|y)\propto \exp\left\{-\frac{y}{2}n_0(x-\mu)^2\right\}$$ ou seja, $X|y\sim\hbox{Normal}(\mu,y^{-1}/n_0)$. Além disso, integrando $f(x,y)$ em $x$, mostramos que

$$f(y)\propto y^{\frac{\nu+1}{2}-1}e^{-\frac{yn_0d^2}{2}}\int_{\mathbb{R}}\exp\left\{-\frac{y}{2}\left[n_0(x-\mu)^2\right]\right\}d\mu\propto y^{\frac{\nu}{2}-1}e^{-\frac{n_0d^2}{2}y}$$ ou seja, $Y\sim\hbox{Gama}(\nu/2, n_0d^2/2)$. Por último, integrando $f(x,y)$ em $y$ teremos

$$\begin{align}f(x)&\propto \int_0^\infty y^{\frac{\nu+1}{2}-1}\exp\left\{-\frac{y}{2}n_0\left[(x-\mu)^2 + d^2\right]\right\}dy \\&\propto \Gamma\left(\frac{\nu+1}{2}\right)\left\{1+\frac{\nu}{d^2}\frac{(x-\mu)^2}{\nu}\right\}^{-\frac{\nu+1}{2}}\end{align}$$ ou seja, $X\sim t_{\nu}(\mu, d^2/\nu)$. Em especial, se $\nu>1$ então $E(X)=\mu$ e, se $\nu>2$ teremos que $$Var(X)=\frac{d^2}{\nu-2}$$

## A função de verossimilhança

Seja $X_1,\ldots,X_n$ uma amostra aleatória do modelo $X|\mu,\phi\sim\hbox{Normal}(\mu,\phi^{-1})$, onde $\phi$, denominado precisão, é o inverso da variância. A função de verossimilhança deste modelo pode ser escrita como

$$L(\mu,\phi)\propto \phi^{\frac{n}{2}}\exp\left\{-\frac{n\phi}{2}(\bar{x}-\mu)^2 -\frac{ns^2\phi}{2}\right\}$$ onde $$s^2=\frac{1}{n}\sum_{i=1}^n(x_i-\bar{x})^2$$ é a estimativa de máxima verossimilhança para $\phi^{-1}$.

## Posteriori com prioris impróprias

Considerando as prioris impróprias $\pi(\phi)\propto \phi^{-1}$, $\pi(\mu)\propto 1$ e que $\pi(\mu,\phi)=\pi(\mu)\pi(\phi)$, teremos que

$$\pi(\mu,\phi|\boldsymbol{x})\propto \phi^{\frac{n}{2}-1}\left\{-\frac{\phi}{2}n\left[ (\bar{x}-\mu)^2 +s^2\right]\right\}$$ ou seja, $\mu,\phi|\boldsymbol{x}\sim\hbox{NG}(\bar{x},n,n-1,s^2)$, o que implica em:

$$\begin{align}
\mu|\phi,\boldsymbol{x}&\sim\hbox{Normal}\left(\bar{x},\frac{\phi^{-1}}{n}\right)\\
\phi|\boldsymbol{x}&\sim\hbox{Gama}\left(\frac{n-1}{2},\frac{ns^2}{2}\right)\\
\mu|\boldsymbol{x}&\sim t_{n-1}\left(\bar{x},\frac{s^2}{n-1}\right)
\end{align}$$

Disto, teremos que

| Parâmetro | Estimativa         | Erro                         |
|-----------|--------------------|------------------------------|
| $\mu$     | $\bar{x}$          | $\frac{s}{\sqrt{n-3}}$       |
| $\phi$    | $\frac{n-1}{ns^2}$ | $\frac{\sqrt{2(n-1)}}{s^2n}$ |

## Posteriori com a priori de Jeffreys

O logaritmo da função de verossimilhança é

$$l(\mu,\phi)=\frac{n}{2}\log\phi -\frac{n}{2}\phi\left[(\bar{x}-\mu)^2 + s^2\right]$$

As derivadas de primeira ordem em $\mu$ e $\phi$ são $$\begin{align}
\frac{\partial}{\partial \mu}l(\mu,\phi)&=n\phi(\bar{x}-\mu)\\
\frac{\partial}{\partial \phi}l(\mu,\phi)&=\frac{n}{2\phi}-\frac{n}{2}\left[(\bar{x}-\mu)^2 + s^2\right]\\
\end{align}$$

e as de segunda ordem são $$\begin{align}
\frac{\partial^2}{\partial \mu^2}l(\mu,\phi)&=-n\phi\\
\frac{\partial^2}{\partial \phi^2}l(\mu,\phi)&=-\frac{n}{2\phi^2}\\
\frac{\partial^2}{\partial \mu\partial \phi}l(\mu,\phi)&=0\\
\end{align}
$$ logo, a matriz de informação de Fisher é $$\mathcal{I}_n(\mu,\phi)=n\left[\begin{array}{cc}\phi & 0 \\0 & \frac{1}{2\phi^2}\end{array}\right],$$ e a priori de Jeffreys é $$\pi(\mu,\phi)\propto \sqrt{|\mathcal{I}_n(\mu,\phi)|}=\phi^{-1/2},$$ que implica na posteriori

$$\pi(\mu,\phi|\boldsymbol{x})\propto \phi^{\frac{n+1}{2}-1}\left\{-\frac{n\phi}{2}\left[(\bar{x}-\mu)^2 +s^2 \right]\right\}$$ ou seja, $\mu,\phi|\boldsymbol{x}\sim\hbox{NG}(\bar{x},n,n,s^2)$, o que implica em:

$$\begin{align}
\mu|\phi,\boldsymbol{x}&\sim\hbox{Normal}\left(\bar{x},\frac{\phi^{-1}}{n}\right)\\
\phi|\boldsymbol{x}&\sim\hbox{Gama}\left(\frac{n}{2},\frac{ns^2}{2}\right)\\
\mu|\boldsymbol{x}&\sim t_{n}\left(\bar{x},\frac{s^2}{n}\right)
\end{align}$$

Disto, teremos que

| Parâmetro | Estimativa        | Erro                           |
|-----------|-------------------|--------------------------------|
| $\mu$     | $\bar{x}$         | $\frac{s}{\sqrt{n-2}}$         |
| $\phi$    | $\frac{1}{s^{2}}$ | $\frac{\sqrt{2}}{s^2\sqrt{n}}$ |

## Posteriori para a priori conjugada

Considere que $(\mu,\phi)\sim \hbox{NG}(m_0,n_0,\nu_0,s^2_0)$. Esta priori é conjugada para o modelo normal, uma vez que

$$\begin{align}
\pi(\mu,\phi|\boldsymbol{x})&\propto \phi^{\frac{n}{2}}\exp\left\{-\frac{\phi}{2}n\left[(\bar{x}-\mu)^2+ s^2\right]\right\}\phi^{\frac{\nu_0+1}{2}-1}\exp\left\{-\frac{\phi}{2}n_0\left[(\mu-m_0)^2 + s_0^2\right]\right\}\\
&\phi^{\frac{\nu_0+n}{2}-1}\exp\left\{-\frac{\phi}{2}\left[n(\bar{x}-\mu)^2 + n_0(\mu-m_0)^2+ns^2 + n_0s^2_0\right]\right\}\end{align}.$$ Como $$n(\bar{x}-\mu)^2 +n_0(\mu-m_0)^2 = (n+n_0)(\mu-m_1)^2+\frac{n n_0}{n+n_0}(\bar{x}-m_0)^2$$ onde $$\begin{align}
m_1&=\frac{n}{n+n_0}\bar{x}+\frac{n_0}{n+n_0}m_0
\end{align},$$ teremos $$\begin{align}
\pi(\mu,\phi|\boldsymbol{x})&\propto \phi^{\frac{\nu_1+1}{2}-1}\exp\left\{-\frac{\phi}{2}n_1\left[(\mu-m_1)^2 + d_1^2\right]\right\}\end{align},$$
onde
$$\begin{align}
\nu_1&=\nu_0+n\\
n_1&=n_0+n\\
m_1&=\frac{n}{n1}\bar{x}+\frac{n_0}{n_1}m_0\\
d_1^2& = \frac{n_0n}{n_1^2}(\bar{x}-m_0)^2+\frac{n}{n_1}s^2 + \frac{n_0}{n_1}s^2_0
\end{align}$$
ou seja, $\mu,\phi|\boldsymbol{x}\sim\hbox{NG}(m_1,n+n_0,\nu_0+n,d_1^2)$, o que implica em:

$$\begin{align}
\mu|\phi,\boldsymbol{x}&\sim\hbox{Normal}\left(m_1,\frac{\phi^{-1}}{n+n_0}\right)\\
\phi|\boldsymbol{x}&\sim\hbox{Gama}\left(\frac{n+\nu_0}{2},\frac{(n+n_0)d_1^2}{2}\right)\\
\mu|\boldsymbol{x}&\sim t_{n}\left(m_1,\frac{d^2_1}{\nu_0+n}\right)
\end{align}$$

Disto, teremos que

| Parâmetro | Estimativa                                    | Erro                                     |
|-------------------------|-----------------------------|------------------|
| $\mu$     | $\frac{n}{n+n_0}\bar{x}+\frac{n_0}{n+n_0}m_0$ | $\frac{d_1}{\sqrt{n+\nu_0-2}}$           |
| $\phi$    | $\frac{n+\nu_0}{(n+n_0)d_1^2}$                | $\frac{\sqrt{2(n+\nu_0)}}{d_1^2(n+n_0)}$ |


## Detecção de outliers

