<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.5.57">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>6&nbsp; Testes de hipóteses – Introdução à Inferência Bayesiana</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./poisson.html" rel="next">
<link href="./bernoulli.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="nav-sidebar floating">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./teste.html"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Testes de hipóteses</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Introdução à Inferência Bayesiana</a> 
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Preface</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./summary.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">summary.html</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./intro.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Introdução</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./conjugada.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Famílias conjugadas</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./estimacao.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">O estimador de bayes</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./bernoulli.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">O modelo Bernoulli</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./teste.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Testes de hipóteses</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./poisson.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">O modelo Poisson</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./normal.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">O modelo normal</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./negativeBinomial.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Binomial negativa</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./aproximacaoNormal.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Aproximação normal e seu uso com o Metropolis-Hastings</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./misturas.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Misturas de distribuições</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./poisson.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">O modelo Poisson</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./mcmc.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Tópicos em Método de Monte Carlo via Cadeias de Markov</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./references.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">References</span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#testes-baseados-na-teoria-da-decisão" id="toc-testes-baseados-na-teoria-da-decisão" class="nav-link active" data-scroll-target="#testes-baseados-na-teoria-da-decisão"><span class="header-section-number">6.1</span> Testes baseados na teoria da decisão</a>
  <ul class="collapse">
  <li><a href="#a-função-de-perda-0-1" id="toc-a-função-de-perda-0-1" class="nav-link" data-scroll-target="#a-função-de-perda-0-1"><span class="header-section-number">6.1.1</span> A Função de Perda 0-1</a></li>
  <li><a href="#a-função-de-perda-a-b" id="toc-a-função-de-perda-a-b" class="nav-link" data-scroll-target="#a-função-de-perda-a-b"><span class="header-section-number">6.1.2</span> A Função de Perda a-b</a></li>
  </ul></li>
  <li><a href="#testes-utilizando-modelos" id="toc-testes-utilizando-modelos" class="nav-link" data-scroll-target="#testes-utilizando-modelos"><span class="header-section-number">6.2</span> Testes utilizando modelos</a></li>
  <li><a href="#o-fator-de-bayes" id="toc-o-fator-de-bayes" class="nav-link" data-scroll-target="#o-fator-de-bayes"><span class="header-section-number">6.3</span> O Fator de Bayes</a></li>
  <li><a href="#exercícios" id="toc-exercícios" class="nav-link" data-scroll-target="#exercícios"><span class="header-section-number">6.4</span> Exercícios</a>
  <ul class="collapse">
  <li><a href="#mudança-de-opinião-sobre-vacinação" id="toc-mudança-de-opinião-sobre-vacinação" class="nav-link" data-scroll-target="#mudança-de-opinião-sobre-vacinação"><span class="header-section-number">6.4.1</span> Mudança de opinião sobre vacinação</a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Testes de hipóteses</span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<section id="testes-baseados-na-teoria-da-decisão" class="level2" data-number="6.1">
<h2 data-number="6.1" class="anchored" data-anchor-id="testes-baseados-na-teoria-da-decisão"><span class="header-section-number">6.1</span> Testes baseados na teoria da decisão</h2>
<section id="a-função-de-perda-0-1" class="level3" data-number="6.1.1">
<h3 data-number="6.1.1" class="anchored" data-anchor-id="a-função-de-perda-0-1"><span class="header-section-number">6.1.1</span> A Função de Perda 0-1</h3>
<p>Considere que <span class="math inline">\(X_1,\ldots,X_n\)</span> é uma amostra do modelo <span class="math inline">\(F(.|\theta)\)</span>. Seja <span class="math inline">\(H_0:\theta\in\Theta_0\)</span> a hipótese nula.</p>
<p>Um teste de hipóteses é uma regra <span class="math inline">\(\varphi(x)\)</span> que recebe o valor 1 se a hipótese <span class="math inline">\(H_0\)</span> é aceita e 0 em caso contrário.</p>
<p>Em relação à natureza da hipótese, observe que <span class="math display">\[I(\theta\in\Theta_0)=\left\{\begin{array}{ll}1,&amp;\hbox{ se }H_0\hbox{ é verdadeira}\\0,&amp;\hbox{ se }H_0\hbox{ é falsa}\end{array}\right..\]</span></p>
<p>Novamente, considere a função de perda quadrática:</p>
<p><span class="math display">\[ \mathcal{L}(\theta,\varphi)=(\varphi(x)-I(\theta\in\Theta_0))^2.\]</span> Definida deste modo, esta função também é denominada Função de Perda 0-1, uma vez que ela assume o valor 0 quando uma decisão correta é tomada e 1 caso contrário.</p>
<p>A esperança a posteriori desta função de perda é</p>
<p><span class="math display">\[E_{\theta|X}(\mathcal{L}(\theta,\varphi))=\int \left(\phi(x)- I(\theta\in\Theta_0)\right)^2 f(\theta|x)d\theta\]</span></p>
<p>e o estimador de Bayes é o valor de <span class="math inline">\(\varphi\)</span> que minimiza a esperança acima. Como <span class="math inline">\(\varphi\)</span> é uma indicadora, teremos duas situações:</p>
<ul>
<li>Se <span class="math inline">\(\phi(x)=0\)</span>, então</li>
</ul>
<p><span class="math display">\[\begin{align}E_{\theta|X}(\mathcal{L}(\theta,\varphi))&amp;=\int I(\theta\in\Theta_0)^2 f(\theta|x)d\theta\\&amp;=\int I(\theta\in\Theta_0) f(\theta|x)d\theta\\&amp;=\int_{\Theta_0 }f(\theta|x)d\theta=P(\theta\in\Theta_0|x)\end{align}\]</span></p>
<ul>
<li>Se <span class="math inline">\(\phi(x)=1\)</span>, então</li>
</ul>
<p><span class="math display">\[\begin{align}E_{\theta|X}(\mathcal{L}(\theta,\varphi))&amp;=\int (1-I(\theta\in\Theta_0)^2 f(\theta|x)d\theta\\&amp;=\int I(\theta\in\Theta_0^c) f(\theta|x)d\theta\\&amp;=\int_{\Theta_0^c }f(\theta|x)d\theta=P(\theta\notin\Theta_0|x)\end{align}\]</span></p>
<p>Deste modo, se <span class="math inline">\(P(\theta\in\Theta_0|x)&gt;P(\theta\in\Theta_0^c|x)\)</span>, temos que <span class="math inline">\(\phi(\boldsymbol{x})=1\)</span> é a decisão que minimiza a perda a posteriori, ou seja, aceitamos <span class="math inline">\(H_0\)</span>. Em caso contrário, rejeitamos <span class="math inline">\(H_0\)</span>.</p>
<div id="exm-" class="theorem example">
<p><span class="theorem-title"><strong>Example 6.1</strong></span> <strong>Fast food</strong></p>
<p>Uma cadeia de <em>fast food</em> deseja saber se vale a pena trocar seus freezers tradicionais, que mantém a carne entre -<span class="math inline">\(17^o\)</span>C e <span class="math inline">\(-9^oC\)</span> por um com uma nova tecnologia (e mais cara!) que mantém a temperatura consistentemente em <span class="math inline">\(-17^oC\)</span>. Para tomar essa decisão, 32 bifes foram armazenados por 8 meses, sendo 16 bifes colocados no freezer tradicional e 16 no novo. Em seguida, um chefe preparou os 32 bifes de maneira idêntica e 16 clientes foram escolhidos ao acaso para avaliar o sabor dos bifes. Cada cliente recebeu um bife de cada freezer, mas a prova foi realizada às cegas.</p>
<p>Podemos considerar a variável <span class="math inline">\(Y_i=1\)</span> se o <span class="math inline">\(i\)</span>-ésimo cliente preferiu o bife armazenado no freezer mais caro e <span class="math inline">\(Y_i=0\)</span> em caso contrário. Deste modo, <span class="math inline">\(Y_1,\ldots,Y_{16}|\theta\sim\hbox{Bernoulli}(\theta)\)</span>. Claramente, estamos interessados em testar <span class="math inline">\(H_0:\theta&gt;1/2\)</span>.</p>
<p>Considere as seguintes prioris:</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="teste_files/figure-html/unnamed-chunk-1-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>A distribuiação a priori Beta(.5,.5) dá mais massa para valores extremos, o que poderia favorecer a hipótese <span class="math inline">\(H_0\)</span>. A priori Beta(1,1) é aquela que parece não dar qualquer preferência. Por último, a priori Beta(2,2) pode ser vista como uma leve resistência à rejeitar que os dois armazenamentos são iguais.</p>
<p>Dos 16 clientes, 13 preferiram os bifes que foram armazenados com a tecnologia mais cara. Como as três prioris acima são casos particulares da distribuição Beta<span class="math inline">\((a,b)\)</span>, decidiremos sobre <span class="math inline">\(H_0\)</span> calculando</p>
<p><span class="math display">\[P(\theta&gt;1/2|\textbf{y})=\int_0^{1/2}\frac{\theta^{13+a-1}(1-\theta)^{3+b-1}}{B(13+a,3+b)}\]</span></p>
<p>que pode ser facilmente obtida com o comando <code>pbeta(.5,13+a,3+b, lower.tail =F)</code> Temos os seguintes resultados:</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Priori</th>
<th><span class="math inline">\(P(H_0|\textbf{y})\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Beta(.5,.5)</td>
<td>0,995</td>
</tr>
<tr class="even">
<td>Uniforme</td>
<td>0,993</td>
</tr>
<tr class="odd">
<td>Beta(2,2)</td>
<td>0,990</td>
</tr>
</tbody>
</table>
<p>Considerando as prioris acima, a probabilidade a posteriori da hipótese nula é de pelo menos 0,99, o que nos leva a concluir que o sabor da carne é melhor preservado no freezer com alta tecnologia</p>
</div>
</section>
<section id="a-função-de-perda-a-b" class="level3" data-number="6.1.2">
<h3 data-number="6.1.2" class="anchored" data-anchor-id="a-função-de-perda-a-b"><span class="header-section-number">6.1.2</span> A Função de Perda a-b</h3>
<p>Suponha que <span class="math inline">\(P(\theta\in\Theta_0|\boldsymbol{x})=0,51\)</span>. Segundo a Função de Perda 0-1, deveríamos aceitar <span class="math inline">\(H_0\)</span>, uma vez que</p>
<p><span class="math display">\[P(\theta\in\Theta_0|\boldsymbol{x})=0,51&gt;0,49=P(\theta\in\Theta_0^c|\boldsymbol{x})\]</span></p>
<p>Isto ocorre porque a perda associada ao erro no teste de hipóteses é igual para qualquer decisão. Podemos associar valores diferentes, reforçando que um erro é mais sério que o outro.</p>
<p>Considere que rejeitar <span class="math inline">\(H_0\)</span> quando ela é verdadeira (erro tipo I) gera uma perda <span class="math inline">\(a\)</span>, enquanto que aceitar <span class="math inline">\(H_0\)</span> quando ela é falsa (erro tipo II) gera uma perda <span class="math inline">\(b\)</span>. Para o erro mais grave, associamos um valor maior para a perda. A função de perda respectiva é denominada Perda <span class="math inline">\(a-b\)</span> e é dada por</p>
<p><span class="math display">\[\mathcal{L}(\theta,\varphi)=\left\{\begin{array}{l}0,\hbox{ se }\varphi(x)=I(\theta\in\Theta_0)\\
a,\hbox{ se }\varphi(x)=0\hbox{ e }\theta\in\Theta_0\\b,\hbox{ se }\varphi(x)=1\hbox{ e }\theta\notin\Theta_0\end{array}\right.\]</span></p>
<p>A média a posteriori dessa função de perda é</p>
<p><span class="math display">\[E_{\theta|\boldsymbol{x}}(\mathcal{L}(\theta,\varphi))=a\int_{\Theta_0}I(\varphi(x)=0)f(\theta|x)d\theta+b\int_{\Theta_0^c}I(\varphi(x)=1)f(\theta|x)d\theta\]</span></p>
<ul>
<li><p>Se <span class="math inline">\(\varphi(x)=1\)</span>, teremos <span class="math display">\[E_{\theta|x}(\mathcal{L}(\theta,\varphi))=b\int_{\Theta_0^c}I(\varphi(x)=1)f(\theta|\boldsymbol{x})d\theta=bP(\theta\in\Theta_0^c|x)\]</span></p></li>
<li><p>Se <span class="math inline">\(\varphi(x)=0\)</span> teremos <span class="math display">\[E_{\theta|x}(\mathcal{L}(\theta,\varphi))=a\int_{\Theta_0}I(\varphi(x)=0)f(\theta|x)d\theta=aP(\theta\in\Theta_0|x)\]</span> logo:</p></li>
<li><p>Se <span class="math inline">\(bP(\theta\in\Theta_0^c|x)&gt;aP(\theta\in\Theta_0|x)\)</span> então a decisão minimiza a perda a posteriori é <span class="math inline">\(\varphi(\boldsymbol{x})=0\)</span>, ou seja, rejeitamos <span class="math inline">\(H_0\)</span>.</p></li>
<li><p>Se <span class="math inline">\(bP(\theta\in\Theta_0^c|x)&lt;aP(\theta\in\Theta_0|x)\)</span> então a decisão minimiza a perda a posteriori é <span class="math inline">\(\varphi(\boldsymbol{x})=1\)</span>, ou seja, aceitamos <span class="math inline">\(H_0\)</span>.</p></li>
</ul>
<p>Na prática, aceitamos <span class="math inline">\(H_0\)</span> se <span class="math display">\[P(\theta\in\Theta_0|\boldsymbol{x})&gt;\frac{b}{b+a}\]</span></p>
<p>Observe que, diferente do ponto de vista frequentista, estamos interessados em aceitar a hipótese <span class="math inline">\(H_0\)</span>. Deste modo, o erro tipo II é o mais preocupante, o que implica em <span class="math inline">\(b&gt;a\)</span>. Na prática, fixamos um valor para <span class="math inline">\(b/(a+b)\)</span>, como 0,95 ou 0,99 e comparamos com <span class="math inline">\(P(\theta\in\Theta_0|\boldsymbol{x})\)</span> para decidir se aceitamos <span class="math inline">\(H_0\)</span>.</p>
<div id="exm-" class="theorem example">
<p><span class="theorem-title"><strong>Example 6.2</strong></span> <strong>Mudança de opinião</strong></p>
<p>Durante a eleição presidencial americana de 1980 um estudo foi conduzido para determinar se um debate televisionado foi capaz de mudar as preferências dos telespectadores pelos candidatos. Foram selecionados 75 adultos aleatoriamente e sua preferência entre os dois candidatos foi registrada. Após a conclusão do detabe, foi perguntado para as mesmas 75 pessoas a sua preferência entre os dois candidatos. Os resultados estão sumariados abaixo.</p>
<p><span class="math display">\[\begin{array}{c|c|c}\hline
\text{Preferência antes } &amp; \text{Preferência depois} &amp; \text{Resultado} \\  
\text{do debate} &amp; \text{do debate} &amp; \\ \hline
\text{Carter} &amp; \text{Carter} &amp; 28 \\
\text{Carter} &amp; \text{Reagan} &amp; 13 \\
\text{Reagan} &amp; \text{Reagan} &amp; 27 \\
\text{Reagan} &amp; \text{Carter} &amp; 7 \\ \hline
\end{array}\]</span></p>
<p>Neste exemplo, vamos testar se os dois candidatos foram igualmente capazes de mudar a opinião dos eleitores.</p>
<p>Sabemos que 20 eleitores mudaram de opinição</p>
<ul>
<li><p><span class="math inline">\(\theta_{CC}\)</span>: a probabilidade do indivíduo preferir o candidato Carter antes de depois do debate</p></li>
<li><p><span class="math inline">\(\theta_{RR}\)</span>: a probabilidade do indivíduo preferir o candidato Reagan antes de depois do debate</p></li>
<li><p><span class="math inline">\(\theta_{CR}\)</span>: a probabilidade do indivíduo preferir o candidato Carter e depois mudar para o Reagan.</p></li>
<li><p><span class="math inline">\(\theta_{RC}\)</span>: a probabilidade do indivíduo preferir o candidato Reagan e depois mudar para o Carter.</p></li>
</ul>
<p>A função de verossimilhança para <span class="math inline">\(\boldsymbol{\theta}=(\theta_{CC},\theta_{CR},\theta_{RC},\theta_{RR})\)</span> é</p>
<p><span class="math display">\[L(\boldsymbol{\theta})\propto \theta_{CC}^{28}\theta_{CR}^{13}\theta_{RR}^{27}\theta_{RC}^{7}.\]</span></p>
<p>Considerando a priori <span class="math inline">\(\boldsymbol{\theta}\sim\hbox{Dirichlet}(1,1,1,1)\)</span>, teremos a posteriori</p>
<p><span class="math display">\[\boldsymbol{\theta}\sim\hbox{Dirichlet}(29,14,28,8),\]</span></p>
<p>Estamos interessados nas probabilidades sobre mudança de opinião, ou seja, em <span class="math inline">\(\theta_{CR}\)</span> e <span class="math inline">\(\theta_{RC}\)</span>, cujas posterioris são <span class="math display">\[\begin{align}
\theta_{CR}&amp;\sim\hbox{Beta}(14,65)\\
\theta_{RC}&amp;\sim\hbox{Beta}(7,68)
\end{align}\]</span></p>
<p>Abaixo, apresentamos as posterioris de <span class="math inline">\(\theta_{CR}\)</span> e <span class="math inline">\(\theta_{RC}\)</span>. Pode-se observar que o candidato Reagan parece ter certa vantagem.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">curve</span>(<span class="fu">dbeta</span>(x,<span class="dv">14</span>,<span class="dv">65</span>), <span class="at">ylim=</span><span class="fu">c</span>(<span class="dv">0</span>,<span class="dv">15</span>), <span class="at">xlim=</span><span class="fu">c</span>(<span class="dv">0</span>,.<span class="dv">5</span>), <span class="at">xlab=</span> <span class="st">'Probabilidade de mudança'</span>, <span class="at">ylab=</span><span class="st">'Densidade a posteriori'</span>, <span class="at">lwd =</span> <span class="dv">2</span>)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">curve</span>(<span class="fu">dbeta</span>(x,<span class="dv">7</span>,<span class="dv">68</span>), <span class="at">add =</span> T, <span class="at">lwd =</span> <span class="dv">2</span>, <span class="at">lty =</span> <span class="dv">2</span>)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">legend</span>(<span class="st">'topright'</span>,<span class="fu">c</span>(<span class="st">'Mudança em favor do Reagan'</span>, <span class="st">'Mudança em favor do Carter'</span>), <span class="at">lwd=</span><span class="dv">2</span>, <span class="at">lty=</span><span class="dv">1</span><span class="sc">:</span><span class="dv">2</span>, <span class="at">bty=</span><span class="st">'n'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="teste_files/figure-html/unnamed-chunk-2-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Vamos testar se o debate do candidato Reagan foi mais eficaz para provocar a mudança de opinião, ou seja, <span class="math inline">\(H:\theta_{RC}&lt;\theta_{CR}\)</span>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="fu">require</span>(extraDistr)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Carregando pacotes exigidos: extraDistr</code></pre>
</div>
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a>B <span class="ot">&lt;-</span> <span class="dv">20000</span></span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>theta <span class="ot">&lt;-</span> <span class="fu">rdirichlet</span>(B, <span class="fu">c</span>(<span class="dv">29</span>,<span class="dv">14</span>,<span class="dv">28</span>,<span class="dv">8</span>))</span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a>thetaCR <span class="ot">&lt;-</span> theta[,<span class="dv">2</span>]</span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a>thetaRC <span class="ot">&lt;-</span> theta[,<span class="dv">4</span>]</span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(thetaRC <span class="sc">&lt;</span> thetaCR)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.9071</code></pre>
</div>
</div>
<p>Não há evidência forte o suficiente para aceitar a superioridade do Reagan para a mudança de opinião. Abaixo, mostramos o gráfico estimado para a posteriori de <span class="math inline">\(\theta_{CR},\theta_{RC}\)</span>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="fu">require</span>(MASS)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Carregando pacotes exigidos: MASS</code></pre>
</div>
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="fu">contour</span>(<span class="fu">kde2d</span>(thetaCR,thetaRC), <span class="at">xlab=</span><span class="fu">expression</span>(theta[CR]),<span class="at">ylab=</span><span class="fu">expression</span>(theta[RC]), <span class="at">lwd =</span> <span class="dv">2</span>)</span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="dv">0</span>,<span class="dv">1</span>,<span class="at">lty=</span><span class="dv">2</span>, <span class="at">lwd =</span> <span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="teste_files/figure-html/unnamed-chunk-4-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</div>
</section>
</section>
<section id="testes-utilizando-modelos" class="level2" data-number="6.2">
<h2 data-number="6.2" class="anchored" data-anchor-id="testes-utilizando-modelos"><span class="header-section-number">6.2</span> Testes utilizando modelos</h2>
<p>Considere novamente o problema dos freezers, da seção anterior. Note que a teoria desenvolvida acima não consegue testar <span class="math inline">\(H_0:\theta=1/2\)</span>, uma vez que este evento possui probabilidade nula a priori.</p>
<p>Para contornar este problema, suponha que existem dois modelos concorrentes:</p>
<ul>
<li><p>Modelo <span class="math inline">\(M_0\)</span>: <span class="math inline">\(y_i\sim\hbox{Bernoulli}(1/2)\)</span></p></li>
<li><p>Modelo <span class="math inline">\(M_1:\)</span></p></li>
</ul>
<p><span class="math display">\[\begin{align}
y_i|\theta&amp;\sim\hbox{Bernoulli}(\theta),\\
\theta&amp;\sim\hbox{Uniforme}(0,1)\end{align}\]</span></p>
<p>Seja <span class="math inline">\(M_0\)</span> o evento no qual o modelo <span class="math inline">\(M_0\)</span> é o verdadeiro gerador da amostra. Observe que <span class="math display">\[f(y_1,\ldots,y_{16}|M_0)=\prod_{i=1}^{16}f(y_i|M_0)=\left(\frac{1}{2}\right)^{16}\]</span></p>
<p>Já para o modelo <span class="math inline">\(M_1\)</span>, observe que</p>
<p><span class="math display">\[\begin{align}f(y_1,\ldots,y_{16}|M_1)&amp;=
\int_0^1 f(y_1,\ldots,y_{16}|\theta)f(\theta)d\theta\\
&amp;=\int_0^1 \prod_{i=1}^{16}f(y_i|\theta)f(\theta)d\theta\\
&amp;=\int_0^1 \prod_{i=1}^{16}\theta^{y_i}(1-\theta)^{1-y_i}d\theta\\
&amp;=\int_0^1\theta^{\sum_{i=1}^{16}y_i}(1-\theta)^{16-\sum_{i=1}^{16}y_i}d\theta=B\left(\sum_{i=1}^{16}y_i+1,16-\sum_{i=1}^{16}y_i+1\right),\end{align}\]</span> onde <span class="math inline">\(B(.,.)\)</span> é a função beta.</p>
<p>Sejam <span class="math inline">\(P(M_0)\)</span> e <span class="math inline">\(P(M_1)=1-P(M_0)\)</span> as probabilidades a priori dos modelos <span class="math inline">\(M_0\)</span> e <span class="math inline">\(M_1\)</span>. Então, a probabilidade a posteriori do modelo <span class="math inline">\(M_0\)</span> é dada por</p>
<p><span class="math display">\[P(M_0|y_1,\ldots,y_{16})=\frac{\left(\frac{1}{2}\right)^{16}P(M_0)}{\left(\frac{1}{2}\right)^{16}P(M_0)+B\left(\sum_{i=1}^{16}y_i+1,16-\sum_{i=1}^{16}y_i+1\right)P(M_1)}\]</span> Ainda considerando o exemplo anterior, assumindo <span class="math inline">\(P(M_0)=P(M_1)=1/2\)</span> e lembrando que <span class="math inline">\(\sum_i y_i=13\)</span>, tem-se</p>
<p><span class="math display">\[P(M_0|y_1,\ldots,y_{16})=\frac{\left(\frac{1}{2}\right)^{17}}{\left(\frac{1}{2}\right)^{17}+B\left(14,4\right)\frac{1}{2}}\approx0,1268,\]</span> o que nos leva a rejeitar <span class="math inline">\(H_0\)</span>.</p>
<div class="alert alert-info">
<p><strong>Caso geral.</strong></p>
<p>Para a amostra <span class="math inline">\(x_1,\ldots,x_n\)</span>, sejam <span class="math inline">\(M_1,\ldots,M_k\)</span> <span class="math inline">\(k\)</span> modelos paramétricos. Sejam <span class="math inline">\(\boldsymbol{\theta}_1,\ldots,\boldsymbol{\theta}_k\)</span>, e <span class="math inline">\(f(\boldsymbol{\theta}_1),\ldots,f(\boldsymbol{\theta}_k)\)</span> seus respectivos parâmetros e prioris. Para determinar o modelo mais adequado:</p>
<ol type="1">
<li><p>Atribua os valores a priori para <span class="math inline">\(P(M_1),\ldots,P(M_k)\)</span></p></li>
<li><p>Para <span class="math inline">\(j=1,\ldots,k\)</span>, calcule <span class="math display">\[f(x_1,\ldots,x_n|M_j)=\int f(x_1,\ldots,x_n|\theta_j)f_j(\theta_j)d\theta_j\]</span></p></li>
<li><p>Compute</p></li>
</ol>
<p><span class="math display">\[P(M_j|x_1,\ldots,x_n)=\frac{f(x_1,\ldots,x_n|M_j)P(M_j)}{\sum_{i=1}^k f(x_1,\ldots,x_n|M_i)P(M_i)}\]</span></p>
<ol start="4" type="1">
<li>Considere como adequado o modelo com maior probabilidade a posteriori</li>
</ol>
</div>
<div class="alert alert-success">
<p><strong>Distribuição preditiva para o caso Bernoulli multivariado</strong></p>
<p>A distribuição <span class="math display">\[f(x)=\int L(\theta)f(\theta)d\theta=E(L(\theta))\]</span> é denominada preditiva. Se <span class="math inline">\(\boldsymbol{X}|\boldsymbol{\theta}\sim\hbox{Bernoulli}(\theta_1,\ldots,\theta_k)\)</span> e considerando o modelo conjugado <span class="math inline">\(\boldsymbol{\theta}\sim\hbox{Dirichlet}(\theta_1,\ldots,\theta_k)\)</span>, teremos que</p>
<p><span class="math display">\[\begin{align}
f(x)&amp;=\int_{\mathcal{S}^k}\prod_{j=1}^k\theta_j^{n_j}\frac{\Gamma(\sum_{j=1}^k a_j)}{\prod_{j=1}^k \Gamma(a_j)}\prod_{j=1}^k \theta_j^{a_j-1}d\boldsymbol{\theta}\\
&amp;=\frac{\Gamma(\sum_{j=1}^k a_j)}{\prod_{j=1}^k \Gamma(a_j)}\int_{\mathcal{S}^k}\prod_{j=1}^k\theta_j^{n_j+a_j-1}d\boldsymbol{\theta}\\
&amp;=\frac{\Gamma(\sum_{j=1}^k a_j)}{\Gamma(n+\sum_{j=1}^k a_j)}\prod_{j=1}^k\frac{\Gamma(a_j+n_j)}{\Gamma(a_j)}
\end{align}\]</span></p>
<p>Além disso, se <span class="math inline">\(a_1=\cdots=a_k=1\)</span>, então</p>
<p><span class="math display">\[f(x)=\frac{(k-1)!}{(n+k-1)!}\prod_{j=1}^k n_j!\]</span></p>
</div>
<div id="exm-" class="theorem example">
<p><span class="theorem-title"><strong>Example 6.3</strong></span> <strong>Imagem corporal</strong></p>
<p>Considere novamente os dados sobre imagem corporal em escolares entre 16 e 17 anos, vistos no capítulo anterior e reproduzidos novamente abaixo.</p>
<p>vamos analisar o recorte dos resultados para alunos entre 16 e 17 anos, diferenciando entre os sexos. As frequências estão sumariadas na tabela abaixo.</p>
<p><span class="math display">\[\begin{array}{c|ccc|c}\hline
&amp;\hbox{Satisfeito} &amp; \hbox{Insatisfeito por excesso} &amp; \hbox{Insatisfeito por magreza} &amp;\hbox{Total}\\ \hline
\hbox{Masculino} &amp; 24 &amp; 10 &amp; 24 &amp; 58 \\
\hbox{Feminino} &amp; 14 &amp; 22 &amp; 24 &amp; 60 \\ \hline
\end{array}
\]</span></p>
<p>Anteriormente, assumimos que as probabilidades entre os sexos deveriam ser diferentes. Denotamos por <span class="math inline">\(\alpha_S,\alpha_E,\alpha_M\)</span> a probabilidade de um indivíduo do sexo masculino ser classificado como Satisfeito, Insatisfeito por Excesso e Insatisfeito por Magreza. Também denotamos por <span class="math inline">\(\beta_S,\beta_E,\beta_M\)</span> as mesmas probabilidades para o sexo feminino. Por último, Utilizamos a priori Dirichlet(1,1,1) para ambos os sexos. Vamos denotar esse modelo por <span class="math inline">\(M_1\)</span>.</p>
<p>Seja <span class="math inline">\(x=(24,10,24)\)</span> as informações registradas para o sexo masculino e <span class="math inline">\(y=(14,22,24)\)</span> as informações para o sexo feminino. Então</p>
<p><span class="math display">\[\begin{align}
f(x,y|M_1)&amp;=f(x|M_1)f(y|M_1)\\
&amp;=\left[\frac{2!}{60!}24!10!24!\right]\left[\frac{2!}{62!}14!22!24!\right]
\end{align}\]</span></p>
<p>Considere agora o modelo <span class="math inline">\(M_2\)</span>, no qual não há diferença entre os sexos. Nesse caso, <span class="math inline">\(x\)</span> e <span class="math inline">\(y\)</span> são provenientes do mesmo modelo, com probabilidades <span class="math inline">\(\gamma_S,\gamma_E,\gamma_M\)</span>, respectivamente. Utilizando a priori Dirichlet(1,1,1), teremos</p>
<p><span class="math display">\[\begin{align}f(x,y|M_2)&amp;=\frac{2!}{120!}38!32!48!\end{align}\]</span></p>
<p>Vamos assumir a priori que <span class="math inline">\(P(M_1)=P(M_2)=1/2\)</span>. Então, vamos testar se não há diferença na percepção da imagem corporal entre os sexos:</p>
<p><span class="math display">\[P(M_2|x,y)=\frac{P(x,y|M_2)}{P(x,y|M_1)+P(x,y|M_2)}\]</span></p>
<p>Vamos realizar esse cálculo no <code>R</code>:</p>
<ul>
<li><span class="math inline">\(P(x,y|M_1)\)</span>:</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="co"># logaritmo da probabilidade:</span></span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>lprobA <span class="ot">&lt;-</span> <span class="fu">lfactorial</span>(<span class="dv">2</span>)<span class="sc">-</span><span class="fu">lfactorial</span>(<span class="dv">60</span>)<span class="sc">+</span><span class="fu">sum</span>(<span class="fu">lfactorial</span>(<span class="fu">c</span>(<span class="dv">24</span>,<span class="dv">10</span>,<span class="dv">24</span>)))</span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a>lprobB <span class="ot">&lt;-</span> <span class="fu">lfactorial</span>(<span class="dv">2</span>)<span class="sc">-</span><span class="fu">lfactorial</span>(<span class="dv">62</span>)<span class="sc">+</span><span class="fu">sum</span>(<span class="fu">lfactorial</span>(<span class="fu">c</span>(<span class="dv">14</span>,<span class="dv">22</span>,<span class="dv">24</span>)))</span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a><span class="co"># probabilidade</span></span>
<span id="cb9-5"><a href="#cb9-5" aria-hidden="true" tabindex="-1"></a>m1 <span class="ot">&lt;-</span> <span class="fu">exp</span>(lprobA <span class="sc">+</span>lprobB)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<ul>
<li><span class="math inline">\(P(x,y|M_2)\)</span>:</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="co"># logaritmo da probabilidade:</span></span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>lprob <span class="ot">&lt;-</span> <span class="fu">lfactorial</span>(<span class="dv">2</span>)<span class="sc">-</span><span class="fu">lfactorial</span>(<span class="dv">120</span>)<span class="sc">+</span><span class="fu">sum</span>( <span class="fu">lfactorial</span>(<span class="fu">c</span>(<span class="dv">38</span>,<span class="dv">32</span>,<span class="dv">48</span>)))</span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a><span class="co"># probabilidade</span></span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a>m2 <span class="ot">&lt;-</span> <span class="fu">exp</span>(lprob)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<ul>
<li><span class="math inline">\(P(M_2|x,y)\)</span></li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a>m2 <span class="sc">/</span> (m1 <span class="sc">+</span> m2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.2824985</code></pre>
</div>
</div>
<p>Portanto, ficamos com o modelo que assume diferença entre os sexos.</p>
</div>
</section>
<section id="o-fator-de-bayes" class="level2" data-number="6.3">
<h2 data-number="6.3" class="anchored" data-anchor-id="o-fator-de-bayes"><span class="header-section-number">6.3</span> O Fator de Bayes</h2>
<p>Anteriormente, vimos que para uma coleção de <span class="math inline">\(k\)</span> modelos competidores, o modelo <span class="math inline">\(M_j\)</span> é preferível aos demais se <span class="math display">\[P(M_j|x)&gt;P(M_i|x).\]</span> para todo <span class="math inline">\(i\neq j\)</span>. Observe que</p>
<p><span class="math display">\[\begin{align}P(M_j|x)&amp;=\frac{f(x|M_j)P(M_j)}{\sum_{i=1}^kf(x|M_j)P(M_j)}\\&amp;=P(M_j)\left[P(M_j)+\sum_{i\neq j}\frac{f(x|M_i)}{f(x|M_j)}P(M_i)\right]^{-1}\\
&amp;=P(M_j)\left[P(M_j)+\sum_{i\neq j}B_{ij}(x)P(M_i)\right]^{-1}\end{align}\]</span> onde a quantidade <span class="math display">\[B_{ij}(x)=\frac{f(x|M_i)}{f(x|M_j)},\]</span> denominada Fator de Bayes, sumariza a informação da amostra para relacionar os modelo <span class="math inline">\(M_i\)</span> e <span class="math inline">\(M_j\)</span>.</p>
<p>Para auxiliar na interpretação do Fator de Bayes, considere o caso com apenas dois modelos onde <span class="math inline">\(P(M_1)=P(M_2)\)</span>. Então <span class="math display">\[\begin{align}P(M_1|x)&amp;=
&amp;=\left[1+B_{21}(x)\right]^{-1}\end{align}\]</span> Observe que, quanto maior for o valor <span class="math inline">\(B_{21}(x)\)</span>, menor será a evidência a favor do modelo <span class="math inline">\(M_1\)</span>.</p>
<p>A escala de Jeffreys pode ser útil para tomada de decisão:</p>
<p><span class="math display">\[\begin{array}{cl}\hline B_{01}(x) &amp; \text{Interpretação}\\ \hline
&gt;100 &amp; \text{Evidência decisiva para } H_0 \\
30-100 &amp; \text{Evidência muito forte para } H_0 \\
10-30 &amp; \text{Evidência forte para } H_0 \\
3-10 &amp; \text{Evidência substancial para } H_0 \\
1-3 &amp; \text{Evidência fraca para } H_0 \\
1/3-1 &amp; \text{Evidência fraca contra } H_0 \\
1/10-1/3 &amp; \text{Evidência substancial contra } H_0 \\
1/30-1/10 &amp; \text{Evidência forte contra } H_0 \\
1/100-1/30 &amp; \text{Evidência muito forte contra } H_0 \\
&lt;1/100 &amp; \text{Evidência decisiva contra } H_0 \\ \hline
\end{array}\]</span></p>
<p>Note que, se <span class="math inline">\(M_0\)</span> é equivalente à <span class="math inline">\(\theta_0\)</span> e <span class="math inline">\(M_1\)</span> é equivalente à <span class="math inline">\(\theta=\theta_1\)</span>, então o Fator de Bayes se torna a estatística do teste de Neyman-Pearson</p>
<p><span class="math display">\[B_{01}(x)=\frac{f(x|\theta_0)}{f(x|\theta_1)}.\]</span></p>
<div id="exm-" class="theorem example">
<p><span class="theorem-title"><strong>Example 6.4</strong></span> <strong>Imagem corporal</strong></p>
<p>Considerando <span class="math inline">\(M_1\)</span> como o modelo no qual as percepções sobre o corpo são provenientes de populações distintas e <span class="math inline">\(M_2\)</span> como o modelo no qual não havia diferença entre os grupos delimitados pelo sexo, obtivemos <span class="math inline">\(P(M_2|x,y)\approx 0,28\)</span>. Utilizando os mesmos comandos em <code>R</code>, teremos que o Fator de Bayes <span class="math inline">\(B_{21}\)</span> é dado por</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a>m2<span class="sc">/</span>m1</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.3937254</code></pre>
</div>
</div>
<p>que gera evidência fraca em favor de <span class="math inline">\(M_1\)</span>.</p>
</div>
<div id="exm-" class="theorem example">
<p><span class="theorem-title"><strong>Example 6.5</strong></span> <strong>Pesquisa Quaest</strong></p>
<p>Uma pesquisa foi realizada entre os dias 27 e 31 de março de 2025 e ouviu 2.024 eleitores presencialmente. Uma das perguntas foi: O quão frustrado você está com o governo Lula hoje? As opções eram 1) Muito frustrado, (2) Pouco frustrado, (3), Nada frustrado e (4) Não sabe/Não respondeu.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 30%">
<col style="width: 32%">
<col style="width: 36%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Categoria</th>
<th style="text-align: center;">Percentual de respostas</th>
<th style="text-align: center;">Número de pessoas (N=2024)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Muito frustrado</td>
<td style="text-align: center;">36%</td>
<td style="text-align: center;">729</td>
</tr>
<tr class="even">
<td style="text-align: left;">Pouco frustrado</td>
<td style="text-align: center;">31%</td>
<td style="text-align: center;">627</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Nada frustrado</td>
<td style="text-align: center;">30%</td>
<td style="text-align: center;">607</td>
</tr>
<tr class="even">
<td style="text-align: left;">Não sabe/Não responderam</td>
<td style="text-align: center;">3%</td>
<td style="text-align: center;">61</td>
</tr>
</tbody>
</table>
<p>Observe que esta é uma pergunta tendenciosa, com uma opção neutra e duas negativas.</p>
<p>Desconsiderando a categoria dos que não responderam, seja <span class="math inline">\(\boldsymbol{\theta}=(\theta_M,\theta_P,\theta_N)\)</span> as probabilidades do indivíduo estar muito, pouco ou nada frustrado, respectivamente.</p>
<p>Considere inicialmente o modelo, denotado por <span class="math inline">\(M_1\)</span>, no qual os entrevistados respondem esta pergunta ao acaso, ou seja <span class="math inline">\(\theta_M=\theta_P=\theta_N=1/3\)</span>. Então</p>
<p><span class="math display">\[P(M_1|\text{dados})=\left(\frac{1}{3}\right)^{2024}\]</span></p>
<p>Em seguida considere o modelo <span class="math inline">\(M_2\)</span>, no qual a verossimilhança é dada por <span class="math display">\[L(\boldsymbol{\theta})\propto \theta_M^{729}\theta_P^{627}\theta_N^{607}.\]</span> Escolhendo a priori <span class="math inline">\(\boldsymbol{\theta}\sim\hbox{Dirichlet}(1,1,1)\)</span>, teremos</p>
<p><span class="math display">\[P(\text{Dados}|M_2)=\frac{2}{2026!}(729!)(627!)(607!)\]</span></p>
<p>O fator de Bayes <span class="math inline">\(B_{21}\)</span> é dado por</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="co"># logP(dados|M2)</span></span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a>logPm2 <span class="ot">&lt;-</span> <span class="sc">-</span><span class="dv">2024</span><span class="sc">*</span><span class="fu">log</span>(<span class="dv">3</span>)</span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-4"><a href="#cb15-4" aria-hidden="true" tabindex="-1"></a><span class="co"># logP(dados|M1)</span></span>
<span id="cb15-5"><a href="#cb15-5" aria-hidden="true" tabindex="-1"></a>logPm1 <span class="ot">&lt;-</span> <span class="fu">log</span>(<span class="dv">2</span>)<span class="sc">+</span><span class="fu">sum</span>(<span class="fu">lfactorial</span>( <span class="fu">c</span>(<span class="dv">729</span>,<span class="dv">627</span>,<span class="dv">607</span>)))<span class="sc">-</span><span class="fu">lfactorial</span>(<span class="dv">1965</span>)</span>
<span id="cb15-6"><a href="#cb15-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-7"><a href="#cb15-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Fator de Bayes</span></span>
<span id="cb15-8"><a href="#cb15-8" aria-hidden="true" tabindex="-1"></a><span class="fu">exp</span>( logPm2 <span class="sc">-</span> logPm1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 1.02445e-29</code></pre>
</div>
</div>
<p>O fator de Bayes é muito pequeno, indicando que a hipótese de que as três probabilidades são iguais não é verdadeira.</p>
</div>
</section>
<section id="exercícios" class="level2" data-number="6.4">
<h2 data-number="6.4" class="anchored" data-anchor-id="exercícios"><span class="header-section-number">6.4</span> Exercícios</h2>
<section id="mudança-de-opinião-sobre-vacinação" class="level3" data-number="6.4.1">
<h3 data-number="6.4.1" class="anchored" data-anchor-id="mudança-de-opinião-sobre-vacinação"><span class="header-section-number">6.4.1</span> Mudança de opinião sobre vacinação</h3>
<p>Uma pesquisadora está investigando a eficácia de uma nova campanha de saúde pública para aumentar a adesão à vacinação contra a gripe em uma determinada comunidade. Ela seleciona uma amostra de 100 indivíduos e registra se cada um tomou a vacina na temporada anterior (Antes da Campanha) e na temporada atual (Depois da Campanha). Os resultados estão apresentado abaixo.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 29%">
<col style="width: 27%">
<col style="width: 32%">
<col style="width: 10%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;"></th>
<th style="text-align: center;">Vacinado Depois</th>
<th style="text-align: center;">Não Vacinado Depois</th>
<th style="text-align: center;">Total</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;"><strong>Vacinado Antes</strong></td>
<td style="text-align: center;">15</td>
<td style="text-align: center;">5</td>
<td style="text-align: center;">20</td>
</tr>
<tr class="even">
<td style="text-align: left;"><strong>Não Vacinado Antes</strong></td>
<td style="text-align: center;">40</td>
<td style="text-align: center;">40</td>
<td style="text-align: center;">80</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><strong>Total</strong></td>
<td style="text-align: center;">55</td>
<td style="text-align: center;">45</td>
<td style="text-align: center;">100</td>
</tr>
</tbody>
</table>
<p>Verifique se a campanha teve um efeito na adesão à vacinação.</p>


</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    // For code content inside modals, clipBoardJS needs to be initialized with a container option
    // TODO: Check when it could be a function (https://github.com/zenorocha/clipboard.js/issues/860)
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./bernoulli.html" class="pagination-link" aria-label="O modelo Bernoulli">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">O modelo Bernoulli</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./poisson.html" class="pagination-link" aria-label="O modelo Poisson">
        <span class="nav-page-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">O modelo Poisson</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->




</body></html>